LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE    := HCFSAPI
LOCAL_SRC_FILES := HCFSAPI.c 
LOCAL_SHARED_LIBRARIES := HCFS_PREBUILT
include $(BUILD_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE    := HCFS_PREBUILT
LOCAL_SRC_FILES := ../mylibs/$(TARGET_ARCH_ABI)/libtest.so
include $(PREBUILT_SHARED_LIBRARY)

#include $(CLEAR_VARS)
#LOCAL_MODULE    := test
#LOCAL_SRC_FILES := test.c
#include $(BUILD_SHARED_LIBRARY)